{
  "formatVersion": "1.1",
  "component": {
    "group": "LRouter",
    "module": "lrouter-gradle-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lrouter-0.0.5.jar",
          "url": "lrouter-0.0.5.jar",
          "size": 36527,
          "sha512": "937ba9cada67bc7c67eaee7769343555763692c9927c27793604ef6fba94000cd77fff6c457ce2a3a7e0f7e2dfe395a3461591703e7f53bbeefe32b2cb312732",
          "sha256": "2cf38c92260a10b34e5ae11e394801b80ce0317dd419fb121914e6c6820ed8d9",
          "sha1": "575016af3b3b9ba60ab2efc3f80433c5d3b3798e",
          "md5": "c194a2139cf83dd5dcb9d4a6710a38ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.billbook.lib",
          "module": "lrouter-api",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.billbook.lib",
          "module": "lrouter-compile-api",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "lrouter-0.0.5.jar",
          "url": "lrouter-0.0.5.jar",
          "size": 36527,
          "sha512": "937ba9cada67bc7c67eaee7769343555763692c9927c27793604ef6fba94000cd77fff6c457ce2a3a7e0f7e2dfe395a3461591703e7f53bbeefe32b2cb312732",
          "sha256": "2cf38c92260a10b34e5ae11e394801b80ce0317dd419fb121914e6c6820ed8d9",
          "sha1": "575016af3b3b9ba60ab2efc3f80433c5d3b3798e",
          "md5": "c194a2139cf83dd5dcb9d4a6710a38ce"
        }
      ]
    }
  ]
}
