{
  "formatVersion": "1.1",
  "component": {
    "group": "LRouter",
    "module": "lrouter-gradle-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lrouter-gradle-plugin-unspecified.jar",
          "url": "lrouter-gradle-plugin-unspecified.jar",
          "size": 35069,
          "sha512": "fcf4404f8d75c5a6f3427d866efe90297a5b9539a6974282f209c66baac20c6b2b36b84cb6fbbd172c0bf619f067e888a84f538ed42ae697b0f0ef8c333c9c54",
          "sha256": "2563ef1614dc9c4da116a635a8cb14d4b2d6e402d659e5b96748b2f466c941d6",
          "sha1": "21eb6816167e8676cc358deb222cb12e56c13249",
          "md5": "c00e6a27a6427bfaa158b873896ecfec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.billbook.lib",
          "module": "lrouter",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "LRouter",
          "module": "lrouter-compile-api",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "lrouter-gradle-plugin-unspecified.jar",
          "url": "lrouter-gradle-plugin-unspecified.jar",
          "size": 35069,
          "sha512": "fcf4404f8d75c5a6f3427d866efe90297a5b9539a6974282f209c66baac20c6b2b36b84cb6fbbd172c0bf619f067e888a84f538ed42ae697b0f0ef8c333c9c54",
          "sha256": "2563ef1614dc9c4da116a635a8cb14d4b2d6e402d659e5b96748b2f466c941d6",
          "sha1": "21eb6816167e8676cc358deb222cb12e56c13249",
          "md5": "c00e6a27a6427bfaa158b873896ecfec"
        }
      ]
    }
  ]
}
