{
  "formatVersion": "1.1",
  "component": {
    "group": "com.billbook.lib",
    "module": "lrouter-compile-api",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.billbook.lib",
          "module": "lrouter-api",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lrouter-compile-api-0.0.1.jar",
          "url": "lrouter-compile-api-0.0.1.jar",
          "size": 8500,
          "sha512": "d9f1ccbfb1edb8874873221acb386ba152067ee77d30608292d80e3cb5b73b23a1bcf0085fd793899094cdbaeb64e5a40be21b4f2302971c043f3ed16ca832a6",
          "sha256": "a0e59e170d6218d548ab2c2a07a28f37e4bd8272bfb917fa87517f825d6558ca",
          "sha1": "419d333fb757365a2233637007ee77208b3cb9a5",
          "md5": "3fb28ebd6c6ffd511ebf8496e18a3ee4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.billbook.lib",
          "module": "lrouter-api",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lrouter-compile-api-0.0.1.jar",
          "url": "lrouter-compile-api-0.0.1.jar",
          "size": 8500,
          "sha512": "d9f1ccbfb1edb8874873221acb386ba152067ee77d30608292d80e3cb5b73b23a1bcf0085fd793899094cdbaeb64e5a40be21b4f2302971c043f3ed16ca832a6",
          "sha256": "a0e59e170d6218d548ab2c2a07a28f37e4bd8272bfb917fa87517f825d6558ca",
          "sha1": "419d333fb757365a2233637007ee77208b3cb9a5",
          "md5": "3fb28ebd6c6ffd511ebf8496e18a3ee4"
        }
      ]
    }
  ]
}
