{
  "formatVersion": "1.1",
  "component": {
    "group": "LRouter",
    "module": "lrouter-gradle-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lrouter-0.0.1.jar",
          "url": "lrouter-0.0.1.jar",
          "size": 35069,
          "sha512": "121365c7a983cb4a7783dbfb194ee50c67b745f5d6d6765a41b667fdbecd508bc93d74d90341f3b0afdae7f46fd0f281105ddebf8f1dfe0b46c986539dad20bc",
          "sha256": "4c4fd2f5734b7675730a84f03c3cad5dc4de42943963df009dcabe28dae04688",
          "sha1": "b051e93edb2e39bea80d6ae3e8817de59cd9d111",
          "md5": "7e8a29dea3481fd6ee0ad7475723df57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.billbook.lib",
          "module": "lrouter-api",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.billbook.lib",
          "module": "lrouter-compile-api",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "lrouter-0.0.1.jar",
          "url": "lrouter-0.0.1.jar",
          "size": 35069,
          "sha512": "121365c7a983cb4a7783dbfb194ee50c67b745f5d6d6765a41b667fdbecd508bc93d74d90341f3b0afdae7f46fd0f281105ddebf8f1dfe0b46c986539dad20bc",
          "sha256": "4c4fd2f5734b7675730a84f03c3cad5dc4de42943963df009dcabe28dae04688",
          "sha1": "b051e93edb2e39bea80d6ae3e8817de59cd9d111",
          "md5": "7e8a29dea3481fd6ee0ad7475723df57"
        }
      ]
    }
  ]
}
