{
  "formatVersion": "1.1",
  "component": {
    "group": "com.billbook.gradle.plugin",
    "module": "lrouter",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javax.inject",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "javax.annotation",
          "module": "jsr250-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lrouter-0.0.1.jar",
          "url": "lrouter-0.0.1.jar",
          "size": 47709,
          "sha512": "6b629e39bba443ec031def0b0a9a352513afb63a9e908634676fe64095bd639222dc126ac3cdd2923ba4f41e2715c123bd3dcd18a4f88fd17e050cbf757039b2",
          "sha256": "883e0f4ef17bc889c991ee313b2b09efe79da20d0130f60999e107d54184463c",
          "sha1": "a46f50b985e183c3ac2ea277eb646c8a7ca6f5ee",
          "md5": "cbdc477ea0d199b5516cf7a5208be5eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javax.inject",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "javax.annotation",
          "module": "jsr250-api",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lrouter-0.0.1.jar",
          "url": "lrouter-0.0.1.jar",
          "size": 47709,
          "sha512": "6b629e39bba443ec031def0b0a9a352513afb63a9e908634676fe64095bd639222dc126ac3cdd2923ba4f41e2715c123bd3dcd18a4f88fd17e050cbf757039b2",
          "sha256": "883e0f4ef17bc889c991ee313b2b09efe79da20d0130f60999e107d54184463c",
          "sha1": "a46f50b985e183c3ac2ea277eb646c8a7ca6f5ee",
          "md5": "cbdc477ea0d199b5516cf7a5208be5eb"
        }
      ]
    }
  ]
}
