{
  "formatVersion": "1.1",
  "component": {
    "group": "LRouter",
    "module": "lrouter-gradle-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lrouter-0.0.12.jar",
          "url": "lrouter-0.0.12.jar",
          "size": 36621,
          "sha512": "c0f0f4704fbb69bae9b73433cc0d028b5c7da4bbc0528bf6cb76fdfb4af4b747eda9a1d69c953fcd0ef28fc919cb81867d88296e69d4fabd5743a3dfcf4d3949",
          "sha256": "8be1768075ff5eb14e87b7cbdc3092bf407b32f195d4e9b0ec6c16c625c836ea",
          "sha1": "6fd1b9165a3f0a5989ba7aa2d02de42d9d02ce05",
          "md5": "e4f02008cbd81d66769e1ba2f751d30f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.billbook.lib",
          "module": "lrouter-api",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.billbook.lib",
          "module": "lrouter-compile-api",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "lrouter-0.0.12.jar",
          "url": "lrouter-0.0.12.jar",
          "size": 36621,
          "sha512": "c0f0f4704fbb69bae9b73433cc0d028b5c7da4bbc0528bf6cb76fdfb4af4b747eda9a1d69c953fcd0ef28fc919cb81867d88296e69d4fabd5743a3dfcf4d3949",
          "sha256": "8be1768075ff5eb14e87b7cbdc3092bf407b32f195d4e9b0ec6c16c625c836ea",
          "sha1": "6fd1b9165a3f0a5989ba7aa2d02de42d9d02ce05",
          "md5": "e4f02008cbd81d66769e1ba2f751d30f"
        }
      ]
    }
  ]
}
